### ISSUE TITLE
Prepare for multiple Redis APIs

### ISSUE THREAD

**Issue by melo** [PerlRedis/perl-redis#35]
The plan for Redis.pm 2.0 is to support multiple APIs:

 * mixed sync/async code like the current version;
 * Promisses-based API;
 * full async API, with initial implementation using AnyEvent.

Also, there will also be a standard API for filters (like to_json/from_json, and encode/decode), scripting (a smarter Redis::ScriptCache), and some meta-commands to manage client connections.

What this means is that instead of creating an instance and using Redis commands as methods of that, you create the Redis instance and then ask for a API object and call methods on that.

This will allow us to have multiple APIs without the risk of collision with Redis commands, and even use multiple APIs (promise and sync, for ex) at the same time over the same connection.

At the same time, all the network code will be moved to "Drivers", with a Driver::PP being included by default with the current code.

This will permit us to add support for HiRedis drivers, or even use RedisDB XS parser.

## Todo's

 - [ ] move Redis.pm code to Redis::V1.pm
 - [ ] Tweak Redis.pm import: if no arguments, use V1, backwards compatible; if the argument is 'v2', use Redis::V2.pm with the new APIs.
 - [ ] extract network code to Redis::Driver::Impl::PP;
 - [ ] code Redis::Drivers::Disco::PP - Redis.pm will load all Disco::* modules, and use them to pick the best Impl to use (in case you don't tell us which one you want to use), and then load only that Impl class
